api_platform:
    title: Movie API
    version: 1.0.0
    graphql:
        enabled: true
    # Good defaults for REST APIs
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header


